### ISSUE TITLE
fix typo: Change Recepient to Recipient

### ISSUE THREAD

**Issue by MarsIfeanyi** [CeoFred/bonpay-react#1]
There is a typo here, please can the spelling of **recepient**. it should be **recipient**

const bonPay = useBonPay({
    value: '0.0001',
    recepient: '0xAFcC4d55a83ae1A449Bee7783A2737aFb5d82254',
    chainId: 5,
    onSuccess,
    onError,
    onClose,
    tokens: ['USDT','DAI','USDC']
  })

**Comment by CeoFred** [comment]
Yea, thanks for spotting that.. i've also updated that in the codebase accordingly.
